
package pl.tjee.bg.projekt.controller.account;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AccountAccess", targetNamespace = "http://model.projekt.bg.tjee.pl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AccountAccess {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "register", targetNamespace = "http://model.projekt.bg.tjee.pl/", className = "pl.tjee.bg.projekt.controller.account.Register")
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://model.projekt.bg.tjee.pl/", className = "pl.tjee.bg.projekt.controller.account.RegisterResponse")
    @Action(input = "http://model.projekt.bg.tjee.pl/AccountAccess/registerRequest", output = "http://model.projekt.bg.tjee.pl/AccountAccess/registerResponse")
    public String register(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://model.projekt.bg.tjee.pl/", className = "pl.tjee.bg.projekt.controller.account.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://model.projekt.bg.tjee.pl/", className = "pl.tjee.bg.projekt.controller.account.LoginResponse")
    @Action(input = "http://model.projekt.bg.tjee.pl/AccountAccess/loginRequest", output = "http://model.projekt.bg.tjee.pl/AccountAccess/loginResponse")
    public String login(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "logout", targetNamespace = "http://model.projekt.bg.tjee.pl/", className = "pl.tjee.bg.projekt.controller.account.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://model.projekt.bg.tjee.pl/", className = "pl.tjee.bg.projekt.controller.account.LogoutResponse")
    @Action(input = "http://model.projekt.bg.tjee.pl/AccountAccess/logoutRequest", output = "http://model.projekt.bg.tjee.pl/AccountAccess/logoutResponse")
    public void logout(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://model.projekt.bg.tjee.pl/", className = "pl.tjee.bg.projekt.controller.account.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://model.projekt.bg.tjee.pl/", className = "pl.tjee.bg.projekt.controller.account.HelloResponse")
    @Action(input = "http://model.projekt.bg.tjee.pl/AccountAccess/helloRequest", output = "http://model.projekt.bg.tjee.pl/AccountAccess/helloResponse")
    public String hello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validateSession", targetNamespace = "http://model.projekt.bg.tjee.pl/", className = "pl.tjee.bg.projekt.controller.account.ValidateSession")
    @ResponseWrapper(localName = "validateSessionResponse", targetNamespace = "http://model.projekt.bg.tjee.pl/", className = "pl.tjee.bg.projekt.controller.account.ValidateSessionResponse")
    @Action(input = "http://model.projekt.bg.tjee.pl/AccountAccess/validateSessionRequest", output = "http://model.projekt.bg.tjee.pl/AccountAccess/validateSessionResponse")
    public boolean validateSession(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
