
package pl.tjee.bg.projekt.controller.account;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AccountAccess", targetNamespace = "http://model.projekt.bg.tjee.pl/", wsdlLocation = "http://localhost:8080/Projekt/AccountAccess?WSDL")
public class AccountAccess_Service
    extends Service
{

    private final static URL ACCOUNTACCESS_WSDL_LOCATION;
    private final static WebServiceException ACCOUNTACCESS_EXCEPTION;
    private final static QName ACCOUNTACCESS_QNAME = new QName("http://model.projekt.bg.tjee.pl/", "AccountAccess");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Projekt/AccountAccess?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACCOUNTACCESS_WSDL_LOCATION = url;
        ACCOUNTACCESS_EXCEPTION = e;
    }

    public AccountAccess_Service() {
        super(__getWsdlLocation(), ACCOUNTACCESS_QNAME);
    }

    public AccountAccess_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACCOUNTACCESS_QNAME, features);
    }

    public AccountAccess_Service(URL wsdlLocation) {
        super(wsdlLocation, ACCOUNTACCESS_QNAME);
    }

    public AccountAccess_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACCOUNTACCESS_QNAME, features);
    }

    public AccountAccess_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccountAccess_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AccountAccess
     */
    @WebEndpoint(name = "AccountAccessPort")
    public AccountAccess getAccountAccessPort() {
        return super.getPort(new QName("http://model.projekt.bg.tjee.pl/", "AccountAccessPort"), AccountAccess.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccountAccess
     */
    @WebEndpoint(name = "AccountAccessPort")
    public AccountAccess getAccountAccessPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://model.projekt.bg.tjee.pl/", "AccountAccessPort"), AccountAccess.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACCOUNTACCESS_EXCEPTION!= null) {
            throw ACCOUNTACCESS_EXCEPTION;
        }
        return ACCOUNTACCESS_WSDL_LOCATION;
    }

}
