
package pl.tjee.bg.projekt.controller.file;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FileAccess", targetNamespace = "http://model.projekt.bg.tjee.pl/", wsdlLocation = "http://localhost:8080/Projekt/FileAccess?WSDL")
public class FileAccess_Service
    extends Service
{

    private final static URL FILEACCESS_WSDL_LOCATION;
    private final static WebServiceException FILEACCESS_EXCEPTION;
    private final static QName FILEACCESS_QNAME = new QName("http://model.projekt.bg.tjee.pl/", "FileAccess");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Projekt/FileAccess?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FILEACCESS_WSDL_LOCATION = url;
        FILEACCESS_EXCEPTION = e;
    }

    public FileAccess_Service() {
        super(__getWsdlLocation(), FILEACCESS_QNAME);
    }

    public FileAccess_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), FILEACCESS_QNAME, features);
    }

    public FileAccess_Service(URL wsdlLocation) {
        super(wsdlLocation, FILEACCESS_QNAME);
    }

    public FileAccess_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FILEACCESS_QNAME, features);
    }

    public FileAccess_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FileAccess_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FileAccess
     */
    @WebEndpoint(name = "FileAccessPort")
    public FileAccess getFileAccessPort() {
        return super.getPort(new QName("http://model.projekt.bg.tjee.pl/", "FileAccessPort"), FileAccess.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FileAccess
     */
    @WebEndpoint(name = "FileAccessPort")
    public FileAccess getFileAccessPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://model.projekt.bg.tjee.pl/", "FileAccessPort"), FileAccess.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FILEACCESS_EXCEPTION!= null) {
            throw FILEACCESS_EXCEPTION;
        }
        return FILEACCESS_WSDL_LOCATION;
    }

}
